
version: "3.7"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./frontend/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
        #      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-manager
    ports:
      - "81:81" # Management UI
      - "8090:8090" # HTTP port
      - "443:443" # HTTPS port
        # - "8443:8443" # HTTPS port
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt

volumes:
  postgres-data:
  npm-data:
  npm-letsencrypt:
